#include "../../include/ui/terminal.h"

#include <stdio.h>
#include <stdlib.h>

/* ──────────────────────────────────────────────────────────────────────
 *  Platform-specific includes
 * ────────────────────────────────────────────────────────────────────── */

#ifdef _WIN32
/*  Windows Console API  */
#include <windows.h>
#include <conio.h>

/* Fallback definitions for older MinGW headers that lack VT support constants */
#ifndef ENABLE_VIRTUAL_TERMINAL_INPUT
#define ENABLE_VIRTUAL_TERMINAL_INPUT   0x0200
#endif
#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif
#ifndef DISABLE_NEWLINE_AUTO_RETURN
#define DISABLE_NEWLINE_AUTO_RETURN     0x0008
#endif

static HANDLE  hStdin  = INVALID_HANDLE_VALUE;
static HANDLE  hStdout = INVALID_HANDLE_VALUE;
static DWORD   orig_in_mode  = 0;
static DWORD   orig_out_mode = 0;
static int     raw_mode_active = 0;

void term_enable_raw_mode(void) {
    if (raw_mode_active) return;

    hStdin  = GetStdHandle(STD_INPUT_HANDLE);
    hStdout = GetStdHandle(STD_OUTPUT_HANDLE);

    /* Save original modes so we can restore later */
    GetConsoleMode(hStdin,  &orig_in_mode);
    GetConsoleMode(hStdout, &orig_out_mode);

    /* Input: disable line input, echo, and processed input (Ctrl-C etc.)   */
    DWORD in_mode = orig_in_mode;
    in_mode &= ~(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT | ENABLE_PROCESSED_INPUT);
    in_mode |= ENABLE_VIRTUAL_TERMINAL_INPUT;
    SetConsoleMode(hStdin, in_mode);

    /* Output: enable virtual terminal processing for ANSI escape codes     */
    DWORD out_mode = orig_out_mode;
    out_mode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING | DISABLE_NEWLINE_AUTO_RETURN;
    SetConsoleMode(hStdout, out_mode);

    raw_mode_active = 1;
}

void term_disable_raw_mode(void) {
    if (!raw_mode_active) return;
    SetConsoleMode(hStdin,  orig_in_mode);
    SetConsoleMode(hStdout, orig_out_mode);
    raw_mode_active = 0;
}

/**
 * Read a single key from the Windows console.
 *
 * We use ReadConsoleInput so we can properly detect escape sequences
 * generated by the virtual terminal input mode.
 */
int term_read_key(void) {
    INPUT_RECORD rec;
    DWORD count;

    for (;;) {
        if (!ReadConsoleInput(hStdin, &rec, 1, &count)) continue;
        if (count == 0) continue;

        if (rec.EventType != KEY_EVENT) continue;
        if (!rec.Event.KeyEvent.bKeyDown) continue;

        WORD  vk = rec.Event.KeyEvent.wVirtualKeyCode;
        char  ch = rec.Event.KeyEvent.uChar.AsciiChar;

        /* Map virtual key codes to our EditorKey values */
        switch (vk) {
            case VK_UP:     return KEY_ARROW_UP;
            case VK_DOWN:   return KEY_ARROW_DOWN;
            case VK_LEFT:   return KEY_ARROW_LEFT;
            case VK_RIGHT:  return KEY_ARROW_RIGHT;
            case VK_HOME:   return KEY_HOME;
            case VK_END:    return KEY_END;
            case VK_DELETE: return KEY_DELETE;
            case VK_PRIOR:  return KEY_PAGE_UP;
            case VK_NEXT:   return KEY_PAGE_DOWN;
            case VK_ESCAPE: return KEY_ESCAPE;
            case VK_BACK:   return KEY_BACKSPACE;
            case VK_RETURN: return '\r';
            case VK_TAB:    return '\t';
            default:
                break;
        }

        /* If it produced a printable ASCII character, return it */
        if (ch >= 32 && ch <= 126) return ch;

        /* Skip everything else (Shift, Ctrl, Alt pressed alone, etc.) */
    }
}

void term_get_window_size(int *rows, int *cols) {
    CONSOLE_SCREEN_BUFFER_INFO csbi;
    if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE), &csbi)) {
        *cols = csbi.srWindow.Right  - csbi.srWindow.Left + 1;
        *rows = csbi.srWindow.Bottom - csbi.srWindow.Top  + 1;
    } else {
        *rows = 24;
        *cols = 80;
    }
}

void term_clear_screen(void) {
    /* Use ANSI escape (VT processing is enabled) */
    printf("\x1b[2J\x1b[H");
    fflush(stdout);
}

#else
/* ──────────────────────────────────────────────────────────────────────
 *  POSIX implementation (Linux / macOS)
 * ────────────────────────────────────────────────────────────────────── */
#include <termios.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <errno.h>

static struct termios orig_termios;
static int raw_mode_active = 0;

void term_disable_raw_mode(void) {
    if (!raw_mode_active) return;
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig_termios);
    raw_mode_active = 0;
}

void term_enable_raw_mode(void) {
    if (raw_mode_active) return;

    tcgetattr(STDIN_FILENO, &orig_termios);
    atexit(term_disable_raw_mode);

    struct termios raw = orig_termios;
    /* Input: no break, no CR-to-NL, no parity, no strip, no flow ctrl */
    raw.c_iflag &= ~(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
    /* Output: disable post-processing */
    raw.c_oflag &= ~(OPOST);
    /* Control: set 8-bit chars */
    raw.c_cflag |= (CS8);
    /* Local: no echo, no canonical, no signals, no extended */
    raw.c_lflag &= ~(ECHO | ICANON | IEXTEN | ISIG);
    /* Read returns after 1 byte, no timeout */
    raw.c_cc[VMIN]  = 1;
    raw.c_cc[VTIME] = 0;

    tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
    raw_mode_active = 1;
}

int term_read_key(void) {
    char c;
    int nread;
    while ((nread = read(STDIN_FILENO, &c, 1)) != 1) {
        if (nread == -1 && errno != EAGAIN) exit(1);
    }

    /* Escape sequence? */
    if (c == '\x1b') {
        char seq[3];
        if (read(STDIN_FILENO, &seq[0], 1) != 1) return KEY_ESCAPE;
        if (read(STDIN_FILENO, &seq[1], 1) != 1) return KEY_ESCAPE;

        if (seq[0] == '[') {
            if (seq[1] >= '0' && seq[1] <= '9') {
                if (read(STDIN_FILENO, &seq[2], 1) != 1) return KEY_ESCAPE;
                if (seq[2] == '~') {
                    switch (seq[1]) {
                        case '1': return KEY_HOME;
                        case '3': return KEY_DELETE;
                        case '4': return KEY_END;
                        case '5': return KEY_PAGE_UP;
                        case '6': return KEY_PAGE_DOWN;
                        case '7': return KEY_HOME;
                        case '8': return KEY_END;
                    }
                }
            } else {
                switch (seq[1]) {
                    case 'A': return KEY_ARROW_UP;
                    case 'B': return KEY_ARROW_DOWN;
                    case 'C': return KEY_ARROW_RIGHT;
                    case 'D': return KEY_ARROW_LEFT;
                    case 'H': return KEY_HOME;
                    case 'F': return KEY_END;
                }
            }
        } else if (seq[0] == 'O') {
            switch (seq[1]) {
                case 'H': return KEY_HOME;
                case 'F': return KEY_END;
            }
        }
        return KEY_ESCAPE;
    }

    /* Map Ctrl-H and 127 to backspace */
    if (c == 127 || c == 8) return KEY_BACKSPACE;

    return c;
}

void term_get_window_size(int *rows, int *cols) {
    struct winsize ws;
    if (ioctl(STDOUT_FILENO, TIOCGWINSZ, &ws) == -1 || ws.ws_col == 0) {
        *rows = 24;
        *cols = 80;
    } else {
        *rows = ws.ws_row;
        *cols = ws.ws_col;
    }
}

void term_clear_screen(void) {
    write(STDOUT_FILENO, "\x1b[2J\x1b[H", 7);
}

#endif /* _WIN32 */
